import hashlib
import os
import threading
from datetime import datetime
from pathlib import Path

from PIL import Image, ImageOps, ImageTk
import tkinter as tk
from tkinter import messagebox, ttk

from .ai_image_editor import (
    AI_EDIT_PRESETS,
    AI_EDIT_WARNING,
    AI_IMAGE_MODEL,
    ai_edit_output_paths,
    ai_edit_provenance,
    build_ai_edit_prompt,
    request_ai_image_edit,
)
from .paths import NOTES_DIR, OUTPUT_DIR


class GalleryWorkflowMixin:
    GALLERY_EXTENSIONS = {".png": "PNG", ".jpg": "JPEG", ".jpeg": "JPEG", ".tif": "TIFF", ".tiff": "TIFF"}
    GALLERY_THUMBNAIL_SIZE = (260, 180)

    @staticmethod
    def gallery_cache_path(path, cache_dir):
        stat = path.stat()
        fingerprint = f"{path.resolve()}|{stat.st_mtime_ns}|{stat.st_size}".encode("utf-8", "replace")
        return Path(cache_dir) / f"{hashlib.sha1(fingerprint).hexdigest()}.jpg"

    @staticmethod
    def gallery_description(path, notes_dir):
        notes_path = Path(notes_dir) / f"{path.stem}_notes.txt"
        if notes_path.is_file():
            try:
                lines = [line.strip() for line in notes_path.read_text(encoding="utf-8", errors="replace").splitlines()]
                useful = [
                    line for line in lines
                    if line and not set(line) <= {"-", "="} and not line.lower().startswith(("file:", "saved:", "created:"))
                ]
                if useful:
                    return useful[0][:240], notes_path
            except OSError:
                pass
        name = path.stem.replace("_", " ").strip()
        if "hydrogen" in name.lower():
            return "Hydrogen-enhanced astronomy image.", None
        if "preview" in name.lower():
            return "Automatically saved color-composite preview.", None
        if "rgb" in name.lower():
            return "Full-resolution color composite.", None
        return "Astronomy image generated by Hubble Workbench.", None

    @classmethod
    def ensure_gallery_thumbnail(cls, record, cache_dir):
        path = Path(record["path"])
        cache_path = cls.gallery_cache_path(path, cache_dir)
        if cache_path.is_file():
            if not record.get("width") or not record.get("height"):
                try:
                    with Image.open(path) as source:
                        record["width"], record["height"] = source.size
                except Exception as exc:
                    record["error"] = str(exc)
            record["thumbnail_path"] = cache_path
            return record
        try:
            with Image.open(path) as source:
                record["width"], record["height"] = source.size
                image = ImageOps.exif_transpose(source).convert("RGB")
                image.thumbnail(cls.GALLERY_THUMBNAIL_SIZE, Image.Resampling.LANCZOS)
                thumbnail = Image.new("RGB", cls.GALLERY_THUMBNAIL_SIZE, "#111827")
                x = (thumbnail.width - image.width) // 2
                y = (thumbnail.height - image.height) // 2
                thumbnail.paste(image, (x, y))
                cache_path.parent.mkdir(parents=True, exist_ok=True)
                thumbnail.save(cache_path, format="JPEG", quality=88, optimize=True)
            record["thumbnail_path"] = cache_path
        except Exception as exc:
            record["error"] = str(exc)
        return record

    @classmethod
    def gallery_image_record(cls, path, notes_dir, cache_dir, generate_thumbnail=True):
        path = Path(path)
        stat = path.stat()
        description, notes_path = cls.gallery_description(path, notes_dir)
        cache_path = cls.gallery_cache_path(path, cache_dir)
        width = height = 0
        error = ""
        if generate_thumbnail:
            try:
                with Image.open(path) as source:
                    width, height = source.size
            except Exception as exc:
                error = str(exc)
        record = {
            "path": path,
            "name": path.name,
            "kind": cls.GALLERY_EXTENSIONS.get(path.suffix.lower(), path.suffix.upper().lstrip(".")),
            "width": int(width),
            "height": int(height),
            "size": int(stat.st_size),
            "modified": float(stat.st_mtime),
            "description": description,
            "notes_path": notes_path,
            "thumbnail_path": cache_path if cache_path.is_file() else None,
            "error": error,
        }
        if generate_thumbnail and not record["thumbnail_path"] and not error:
            cls.ensure_gallery_thumbnail(record, cache_dir)
        return record

    @classmethod
    def discover_gallery_images(
        cls,
        output_dir=OUTPUT_DIR,
        notes_dir=NOTES_DIR,
        cache_dir=None,
        generate_thumbnails=True,
    ):
        output_dir = Path(output_dir)
        notes_dir = Path(notes_dir)
        cache_dir = Path(cache_dir or output_dir / ".gallery_cache")
        if not output_dir.exists():
            return []
        paths = [
            path for path in output_dir.rglob("*")
            if path.is_file()
            and cache_dir not in path.parents
            and path.suffix.lower() in cls.GALLERY_EXTENSIONS
        ]
        paths.sort(key=lambda path: path.stat().st_mtime, reverse=True)
        return [
            cls.gallery_image_record(
                path,
                notes_dir,
                cache_dir,
                generate_thumbnail=generate_thumbnails,
            )
            for path in paths
        ]

    @staticmethod
    def filter_gallery_items(items, query="", kind="All", sort_order="Newest"):
        query = str(query or "").strip().lower()
        selected = [
            item for item in items
            if (kind == "All" or item.get("kind") == kind)
            and (
                not query
                or query in item.get("name", "").lower()
                or query in item.get("description", "").lower()
            )
        ]
        if sort_order == "Oldest":
            selected.sort(key=lambda item: item.get("modified", 0))
        elif sort_order == "Name":
            selected.sort(key=lambda item: item.get("name", "").lower())
        else:
            selected.sort(key=lambda item: item.get("modified", 0), reverse=True)
        return selected

    @staticmethod
    def gallery_item_details(item):
        if not item:
            return "Select an image to see its details."
        modified = datetime.fromtimestamp(item.get("modified", 0)).strftime("%Y-%m-%d %H:%M:%S")
        dimensions = (
            f"{item.get('width', 0):,} x {item.get('height', 0):,} pixels"
            if item.get("width") and item.get("height")
            else "Unavailable"
        )
        lines = [
            item.get("name", ""),
            "=" * 48,
            "",
            item.get("description", ""),
            "",
            f"Type: {item.get('kind', '')}",
            f"Dimensions: {dimensions}",
            f"File size: {item.get('size', 0) / (1024 * 1024):.2f} MB",
            f"Modified: {modified}",
            f"Location: {item.get('path', '')}",
        ]
        if item.get("notes_path"):
            lines.append(f"Notes: {item['notes_path']}")
        if item.get("error"):
            lines.extend(("", f"Thumbnail warning: {item['error']}"))
        return "\n".join(lines)

    def build_gallery_tab(self):
        toolbar = ttk.Frame(self.gallery_tab)
        toolbar.pack(fill="x", pady=(0, 8))
        ttk.Label(toolbar, text="Search").pack(side="left")
        self.gallery_search_var = tk.StringVar(value="")
        ttk.Entry(toolbar, textvariable=self.gallery_search_var, width=28).pack(side="left", padx=(6, 10))
        self.gallery_type_var = tk.StringVar(value="All")
        ttk.Combobox(
            toolbar,
            textvariable=self.gallery_type_var,
            values=["All", "PNG", "TIFF", "JPEG"],
            state="readonly",
            width=8,
        ).pack(side="left")
        self.gallery_sort_var = tk.StringVar(value="Newest")
        ttk.Combobox(
            toolbar,
            textvariable=self.gallery_sort_var,
            values=["Newest", "Oldest", "Name"],
            state="readonly",
            width=9,
        ).pack(side="left", padx=(6, 10))
        ttk.Button(toolbar, text="Refresh", command=lambda: self.refresh_gallery_async()).pack(side="left")
        ttk.Button(toolbar, text="Open Outputs Folder", command=lambda: self.open_folder(OUTPUT_DIR)).pack(side="left", padx=(6, 0))
        self.gallery_status_var = tk.StringVar(value="Gallery is preparing...")
        ttk.Label(toolbar, textvariable=self.gallery_status_var).pack(side="left", padx=(12, 0))
        self.enable_responsive_toolbar(toolbar)

        body = tk.PanedWindow(self.gallery_tab, orient="horizontal", bd=0, relief="flat", sashwidth=6, bg="#d1d5db")
        body.pack(fill="both", expand=True)
        gallery_panel = ttk.Frame(body)
        details_panel = ttk.Frame(body)
        body.add(gallery_panel, stretch="always", minsize=420)
        body.add(details_panel, stretch="never", minsize=260, width=320)
        self.enable_responsive_split_pane(body, self.gallery_tab)

        self.gallery_canvas = tk.Canvas(gallery_panel, bg="#eef2f7", highlightthickness=0)
        scrollbar = ttk.Scrollbar(gallery_panel, orient="vertical", command=self.gallery_canvas.yview)
        self.gallery_canvas.configure(yscrollcommand=scrollbar.set)
        self.gallery_canvas.pack(side="left", fill="both", expand=True)
        scrollbar.pack(side="right", fill="y")
        self.gallery_grid = ttk.Frame(self.gallery_canvas, padding=8)
        self.gallery_grid_window = self.gallery_canvas.create_window((0, 0), window=self.gallery_grid, anchor="nw")
        self.gallery_grid.bind("<Configure>", lambda _event: self.gallery_canvas.configure(scrollregion=self.gallery_canvas.bbox("all")))
        self.gallery_canvas.bind("<Configure>", self.gallery_canvas_resized)
        self.gallery_canvas.bind(
            "<MouseWheel>",
            lambda event: self.gallery_canvas.yview_scroll(-max(1, int(event.delta / 120)), "units"),
        )

        details_tools = ttk.Frame(details_panel)
        details_tools.pack(fill="x", pady=(0, 6))
        ttk.Button(details_tools, text="Open Image", command=lambda: self.open_selected_gallery_image()).pack(side="left")
        ttk.Button(details_tools, text="Copy Path", command=lambda: self.copy_selected_gallery_path()).pack(side="left", padx=(6, 0))
        ttk.Button(details_tools, text="Open Notes", command=lambda: self.open_selected_gallery_notes()).pack(side="left", padx=(6, 0))
        ttk.Button(
            details_tools,
            text="AI Creative Edit (Account Required)",
            command=self.open_ai_image_editor,
        ).pack(side="left", padx=(6, 0))
        self.enable_responsive_toolbar(details_tools)
        self.gallery_details_text = tk.Text(details_panel, wrap="word", bg="#ffffff", fg="#1f1f1f", relief="flat", padx=10, pady=10)
        self.gallery_details_text.pack(fill="both", expand=True)
        self.gallery_details_text.insert("1.0", self.gallery_item_details(None))

        self.gallery_items = []
        self.gallery_selected_item = None
        self.gallery_thumbnail_photos = []
        self.gallery_columns = 0
        self.gallery_search_var.trace_add("write", lambda *_args: self.render_gallery())
        self.gallery_type_var.trace_add("write", lambda *_args: self.render_gallery())
        self.gallery_sort_var.trace_add("write", lambda *_args: self.render_gallery())
        self.after(150, self.refresh_gallery_async)

    def refresh_gallery_async(self):
        self.gallery_status_var.set("Scanning outputs and preparing thumbnails...")

        def worker():
            try:
                items = self.discover_gallery_images(generate_thumbnails=False)
                error = None
            except Exception as exc:
                items, error = [], exc
            self.after(0, lambda: self.finish_gallery_refresh(items, error))

        threading.Thread(target=worker, daemon=True).start()

    def finish_gallery_refresh(self, items, error=None):
        if error:
            self.gallery_status_var.set(f"Gallery refresh failed: {error}")
            return
        self.gallery_items = list(items)
        self.render_gallery()
        self.start_gallery_thumbnail_worker()

    def start_gallery_thumbnail_worker(self):
        items = [
            item for item in getattr(self, "gallery_items", [])
            if (
                not item.get("thumbnail_path")
                or not item.get("width")
                or not item.get("height")
            )
            and not item.get("error")
        ]
        if not items:
            return
        cache_dir = OUTPUT_DIR / ".gallery_cache"
        total = len(items)

        def worker():
            for index, item in enumerate(items, start=1):
                self.ensure_gallery_thumbnail(item, cache_dir)
                self.after(
                    0,
                    lambda completed=index, count=total: self.finish_gallery_thumbnail(completed, count),
                )

        threading.Thread(target=worker, daemon=True).start()

    def finish_gallery_thumbnail(self, completed, total):
        self.render_gallery()
        self.gallery_status_var.set(
            f"Showing {len(self.filter_gallery_items(self.gallery_items, self.gallery_search_var.get(), self.gallery_type_var.get(), self.gallery_sort_var.get()))} "
            f"image(s). Prepared thumbnail {completed} of {total}."
        )

    def gallery_canvas_resized(self, event):
        columns = max(1, int(event.width) // 286)
        self.gallery_canvas.itemconfigure(self.gallery_grid_window, width=max(280, event.width))
        if columns != self.gallery_columns:
            self.gallery_columns = columns
            self.render_gallery()

    def render_gallery(self):
        if not hasattr(self, "gallery_grid"):
            return
        for child in self.gallery_grid.winfo_children():
            child.destroy()
        self.gallery_thumbnail_photos = []
        items = self.filter_gallery_items(
            getattr(self, "gallery_items", []),
            self.gallery_search_var.get(),
            self.gallery_type_var.get(),
            self.gallery_sort_var.get(),
        )
        columns = max(1, self.gallery_columns or 1)
        for index, item in enumerate(items):
            row, column = divmod(index, columns)
            card = ttk.Frame(self.gallery_grid, padding=7, relief="ridge")
            card.grid(row=row, column=column, sticky="nsew", padx=5, pady=5)
            image_label = ttk.Label(card, anchor="center")
            image_label.pack(fill="x")
            thumbnail_path = item.get("thumbnail_path")
            if thumbnail_path and Path(thumbnail_path).is_file():
                try:
                    with Image.open(thumbnail_path) as thumbnail:
                        photo = ImageTk.PhotoImage(thumbnail.copy())
                    self.gallery_thumbnail_photos.append(photo)
                    image_label.configure(image=photo)
                except Exception:
                    image_label.configure(text="Thumbnail unavailable", width=32)
            else:
                image_label.configure(text="Thumbnail unavailable", width=32)
            ttk.Label(card, text=item.get("name", ""), wraplength=248, font=("Segoe UI", 9, "bold")).pack(fill="x", pady=(6, 2))
            ttk.Label(card, text=item.get("description", ""), wraplength=248).pack(fill="x")
            date_text = datetime.fromtimestamp(item.get("modified", 0)).strftime("%Y-%m-%d %H:%M")
            ttk.Label(card, text=f"{item.get('kind', '')} • {date_text}", foreground="#4b5563").pack(fill="x", pady=(4, 0))
            for widget in (card, image_label, *card.winfo_children()):
                widget.bind("<Button-1>", lambda _event, selected=item: self.select_gallery_item(selected))
                widget.bind("<Double-Button-1>", lambda _event, selected=item: self.open_gallery_item(selected))
        for column in range(columns):
            self.gallery_grid.columnconfigure(column, weight=1)
        self.gallery_status_var.set(f"Showing {len(items)} of {len(getattr(self, 'gallery_items', []))} image(s).")

    def select_gallery_item(self, item):
        self.gallery_selected_item = item
        self.gallery_details_text.delete("1.0", "end")
        self.gallery_details_text.insert("1.0", self.gallery_item_details(item))

    def open_gallery_item(self, item):
        path = Path(item.get("path", ""))
        if not path.is_file():
            self.gallery_status_var.set("The selected image is no longer available. Refresh the gallery.")
            return False
        self.open_file(path)
        self.gallery_status_var.set(f"Opened {path.name}")
        return True

    def open_selected_gallery_image(self):
        if not self.gallery_selected_item:
            self.gallery_status_var.set("Select an image first.")
            return False
        return self.open_gallery_item(self.gallery_selected_item)

    def copy_selected_gallery_path(self):
        if not self.gallery_selected_item:
            self.gallery_status_var.set("Select an image first.")
            return False
        path = str(self.gallery_selected_item.get("path", ""))
        self.clipboard_clear()
        self.clipboard_append(path)
        self.gallery_status_var.set("Copied the selected image path.")
        return True

    def open_selected_gallery_notes(self):
        if not self.gallery_selected_item or not self.gallery_selected_item.get("notes_path"):
            self.gallery_status_var.set("No companion notes were found for the selected image.")
            return False
        self.open_file(Path(self.gallery_selected_item["notes_path"]))
        return True

    def open_ai_image_editor(self):
        if not self.gallery_selected_item:
            self.gallery_status_var.set("Select an image first.")
            return False
        source_path = Path(self.gallery_selected_item.get("path", ""))
        if not source_path.is_file():
            self.gallery_status_var.set("The selected image is no longer available. Refresh the gallery.")
            return False

        dialog = tk.Toplevel(self)
        dialog.title("AI Creative Edit — Account Required")
        dialog.geometry("660x600")
        dialog.minsize(520, 480)
        dialog.transient(self)

        body = ttk.Frame(dialog, padding=14)
        body.pack(fill="both", expand=True)
        ttk.Label(body, text="AI Creative Edit", font=("Segoe UI", 13, "bold")).pack(anchor="w")
        ttk.Label(
            body,
            text=f"Editing model: {AI_IMAGE_MODEL}",
            foreground="#4b5563",
        ).pack(anchor="w", pady=(1, 0))
        ttk.Label(body, text=source_path.name, wraplength=610).pack(anchor="w", pady=(2, 10))
        ttk.Label(
            body,
            text=AI_EDIT_WARNING,
            foreground="#9a3412",
            wraplength=610,
            justify="left",
        ).pack(fill="x", pady=(0, 12))

        ttk.Label(body, text="Editing style").pack(anchor="w")
        preset_var = tk.StringVar(value=next(iter(AI_EDIT_PRESETS)))
        ttk.Combobox(
            body,
            textvariable=preset_var,
            values=list(AI_EDIT_PRESETS),
            state="readonly",
        ).pack(fill="x", pady=(3, 10))

        ttk.Label(body, text="Additional instructions (optional)").pack(anchor="w")
        instructions = tk.Text(body, height=8, wrap="word")
        instructions.pack(fill="both", expand=True, pady=(3, 10))
        instructions.insert(
            "1.0",
            "Improve this image while keeping the astronomical subject recognizable.",
        )

        options = ttk.Frame(body)
        options.pack(fill="x")
        ttk.Label(options, text="Quality").pack(side="left")
        quality_var = tk.StringVar(value="medium")
        ttk.Combobox(
            options,
            textvariable=quality_var,
            values=["low", "medium", "high"],
            state="readonly",
            width=10,
        ).pack(side="left", padx=(6, 12))

        key_row = ttk.Frame(body)
        key_row.pack(fill="x", pady=(10, 0))
        ttk.Label(key_row, text="OpenAI API key").pack(side="left")
        api_key_var = tk.StringVar(value=os.environ.get("OPENAI_API_KEY", "").strip())
        ttk.Entry(key_row, textvariable=api_key_var, show="•").pack(
            side="left", fill="x", expand=True, padx=(8, 0)
        )
        ttk.Label(
            body,
            text="Used for this edit only and never saved by Workbench.",
            foreground="#4b5563",
        ).pack(anchor="w", pady=(2, 0))

        acknowledgement_var = tk.BooleanVar(value=False)
        ttk.Checkbutton(
            body,
            text="I understand this output may contain invented details and is not scientific data.",
            variable=acknowledgement_var,
        ).pack(anchor="w", pady=(12, 8))

        status_var = tk.StringVar(
            value="Your original will remain unchanged. API usage is billed to your OpenAI account."
        )
        ttk.Label(body, textvariable=status_var, wraplength=610).pack(fill="x", pady=(0, 8))

        buttons = ttk.Frame(body)
        buttons.pack(fill="x")
        ttk.Button(
            buttons,
            text="Account / API Key Setup",
            command=lambda: self.open_file("https://platform.openai.com/api-keys"),
        ).pack(side="left")
        run_button = ttk.Button(buttons, text="Create AI Edit")
        run_button.pack(side="right")
        ttk.Button(buttons, text="Cancel", command=dialog.destroy).pack(side="right", padx=(0, 6))

        def update_run_state(*_args):
            run_button.configure(
                state=(
                    "normal"
                    if api_key_var.get().strip() and acknowledgement_var.get()
                    else "disabled"
                )
            )

        acknowledgement_var.trace_add("write", update_run_state)
        api_key_var.trace_add("write", update_run_state)
        update_run_state()
        run_button.configure(
            command=lambda: self.start_ai_image_edit(
                dialog,
                source_path,
                api_key_var.get(),
                preset_var.get(),
                instructions.get("1.0", "end").strip(),
                quality_var.get(),
                run_button,
                status_var,
            )
        )
        dialog.grab_set()
        return True

    def start_ai_image_edit(
        self,
        dialog,
        source_path,
        api_key,
        preset,
        instructions,
        quality,
        run_button,
        status_var,
    ):
        api_key = str(api_key or "").strip()
        if not api_key:
            status_var.set("Enter an OpenAI API key, or use Account / API Key Setup first.")
            return False
        prompt = build_ai_edit_prompt(preset, instructions)
        output_path, notes_path = ai_edit_output_paths(source_path, OUTPUT_DIR, NOTES_DIR)
        run_button.configure(state="disabled")
        status_var.set("Sending a reduced PNG copy to OpenAI. This can take a few minutes...")
        self.gallery_status_var.set(f"AI Creative Edit is processing {source_path.name}...")

        def worker():
            try:
                image_data = request_ai_image_edit(api_key, source_path, prompt, quality)
                output_path.parent.mkdir(parents=True, exist_ok=True)
                notes_path.parent.mkdir(parents=True, exist_ok=True)
                output_path.write_bytes(image_data)
                notes_path.write_text(
                    ai_edit_provenance(source_path, output_path, prompt, quality),
                    encoding="utf-8",
                )
                error = None
            except Exception as exc:
                error = exc
            self.after(
                0,
                lambda: self.finish_ai_image_edit(
                    dialog, output_path, notes_path, run_button, status_var, error
                ),
            )

        threading.Thread(target=worker, daemon=True).start()
        return True

    def finish_ai_image_edit(
        self,
        dialog,
        output_path,
        notes_path,
        run_button,
        status_var,
        error=None,
    ):
        if error:
            run_button.configure(state="normal")
            status_var.set(f"AI edit failed: {error}")
            self.gallery_status_var.set(f"AI Creative Edit failed: {error}")
            messagebox.showerror("AI Creative Edit", str(error), parent=dialog)
            return
        self.gallery_status_var.set(
            f"Saved AI creative edit and provenance note: {output_path.name}"
        )
        self.refresh_gallery_async()
        dialog.destroy()
        self.open_file(output_path)
